### ISSUE TITLE
Can't run it in Jupyterlab?

### ISSUE THREAD

**Issue by kwon14** [qtangs/sagemaker-notebook-container#5]
Hi.!
I am so happy thanks to your useful code.

I have one question.
If you look at the attached image below,
AWS DOCS could see the example screen open in Jupyterlab.
(https://docs.aws.amazon.com/sagemaker/latest/dg/howitworks-nbexamples.html)

I am wondering if there is any executable code or dockerfile in Jupyterlab.

Thank you so much for continuing, and ask for answers :)

![screen](https://user-images.githubusercontent.com/64061288/96415529-b421b880-1229-11eb-980e-0efb5743f587.png)

**Comment by qtangs** [comment]
The files in the image are ipython notebooks, you can open them in Jupyter notebook to run.
